#pragma once

#ifndef VECTOR_CANYON_EXPLICIT_STATIC_BASELINE
#define VECTOR_CANYON_EXPLICIT_STATIC_BASELINE 0
#endif

#ifndef VECTOR_CANYON_EXPLICIT_PREVIEW
#define VECTOR_CANYON_EXPLICIT_PREVIEW 0
#endif

#ifndef VECTOR_CANYON_EXPLICIT_TOP_DEBUG
#define VECTOR_CANYON_EXPLICIT_TOP_DEBUG 0
#endif

#ifndef VECTOR_CANYON_EXPLICIT_EVENT_STREAM
#define VECTOR_CANYON_EXPLICIT_EVENT_STREAM 0
#endif

static_assert(VECTOR_CANYON_EXPLICIT_STATIC_BASELINE == 0 || VECTOR_CANYON_EXPLICIT_STATIC_BASELINE == 1,
              "VECTOR_CANYON_EXPLICIT_STATIC_BASELINE must be 0 or 1");
static_assert(VECTOR_CANYON_EXPLICIT_PREVIEW == 0 || VECTOR_CANYON_EXPLICIT_PREVIEW == 1,
              "VECTOR_CANYON_EXPLICIT_PREVIEW must be 0 or 1");
static_assert(VECTOR_CANYON_EXPLICIT_TOP_DEBUG == 0 || VECTOR_CANYON_EXPLICIT_TOP_DEBUG == 1,
              "VECTOR_CANYON_EXPLICIT_TOP_DEBUG must be 0 or 1");
static_assert(VECTOR_CANYON_EXPLICIT_EVENT_STREAM == 0 || VECTOR_CANYON_EXPLICIT_EVENT_STREAM == 1,
              "VECTOR_CANYON_EXPLICIT_EVENT_STREAM must be 0 or 1");
static_assert(VECTOR_CANYON_EXPLICIT_PREVIEW || !VECTOR_CANYON_EXPLICIT_TOP_DEBUG,
              "The top debug camera requires explicit preview mode");
static_assert(VECTOR_CANYON_EXPLICIT_PREVIEW || !VECTOR_CANYON_EXPLICIT_EVENT_STREAM,
              "The isolated event stream requires explicit preview mode");
static_assert(!VECTOR_CANYON_EXPLICIT_STATIC_BASELINE || !VECTOR_CANYON_EXPLICIT_EVENT_STREAM,
              "The straight baseline and event stream cannot be enabled together");
