#pragma once

#ifndef VECTOR_CANYON_EXPLICIT_TERRAIN
#define VECTOR_CANYON_EXPLICIT_TERRAIN 1
#endif

#ifndef VECTOR_CANYON_EXPLICIT_STATIC_BASELINE
#define VECTOR_CANYON_EXPLICIT_STATIC_BASELINE 1
#endif

static_assert(VECTOR_CANYON_EXPLICIT_TERRAIN == 0 || VECTOR_CANYON_EXPLICIT_TERRAIN == 1,
              "VECTOR_CANYON_EXPLICIT_TERRAIN must be 0 or 1");
static_assert(VECTOR_CANYON_EXPLICIT_STATIC_BASELINE == 0 || VECTOR_CANYON_EXPLICIT_STATIC_BASELINE == 1,
              "VECTOR_CANYON_EXPLICIT_STATIC_BASELINE must be 0 or 1");
static_assert(VECTOR_CANYON_EXPLICIT_TERRAIN || !VECTOR_CANYON_EXPLICIT_STATIC_BASELINE,
              "The static explicit baseline requires explicit terrain");
