#!/usr/bin/env python3
"""Bake a C2 module route into distance-indexed Hermite nodes (standard library)."""
import bisect
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NODES = 512
BASE = 0.35

def add(a, b): return tuple(x+y for x, y in zip(a, b))
def mul(a, s): return tuple(x*s for x in a)
def sub(a, b): return add(a, mul(b, -1))
def norm(a): return math.sqrt(sum(x*x for x in a))
def unit(a): return mul(a, 1/norm(a))
def smooth(t): return 10*t**3-15*t**4+6*t**5
def smooth_d(t): return 30*t*t*(1-t)**2
def smooth_dd(t): return 60*t*(1-t)*(1-2*t)

def polynomial(p, q, v, w, a=(0,0,0), b=(0,0,0)):
    c = [p, v, mul(a, .5)]
    d = sub(q, add(add(c[0], c[1]), c[2]))
    e = sub(w, add(c[1], mul(c[2], 2)))
    f = sub(b, mul(c[2], 2))
    c += [add(add(mul(d,10),mul(e,-4)),mul(f,.5)),
          add(add(mul(d,-15),mul(e,7)),mul(f,-1)),
          add(add(mul(d,6),mul(e,-3)),mul(f,.5))]
    return c

def evaluate(c, t):
    return tuple(sum(c[i][j]*t**i for i in range(6)) for j in range(3))
def derivative(c, t):
    return tuple(sum(i*c[i][j]*t**(i-1) for i in range(1,6)) for j in range(3))
def second(c, t):
    return tuple(sum(i*(i-1)*c[i][j]*t**(i-2) for i in range(2,6)) for j in range(3))

def arc(cx, cz, radius, begin, end, h0, h1, pieces):
    result=[]
    angle=end-begin
    for i in range(pieces):
        ends=[]
        for j in (i,i+1):
            u=j/pieces; theta=begin+angle*u; omega=angle/pieces
            p=(cx+radius*math.cos(theta), BASE+h0+(h1-h0)*smooth(u),cz+radius*math.sin(theta))
            v=(-radius*math.sin(theta)*omega,(h1-h0)*smooth_d(u)/pieces,radius*math.cos(theta)*omega)
            a=(-radius*math.cos(theta)*omega**2,(h1-h0)*smooth_dd(u)/pieces**2,-radius*math.sin(theta)*omega**2)
            # Straight-to-arc transitions have zero curvature at the joint.
            if j in (0,pieces): a=(0,0,0)
            ends.append((p,v,a))
        (p,v,a),(q,w,b)=ends
        result.append(polynomial(p,q,v,w,a,b))
    return result

def straight(p, q):
    v=(q[0]-p[0],0,q[2]-p[2])
    return polynomial(p,q,v,v)

def build():
    pi=math.pi
    modules=arc(-12,0,10,-pi/2,3*pi/2,0,10,4)
    modules.append(straight((-12,BASE+10,-10),(12,BASE+16,-10)))
    modules += arc(12,-5,5,-pi/2,pi/2,16,16,2)
    modules.append(straight((12,BASE+16,0),(-34,BASE+13,0)))
    modules += arc(-34,-14,14,pi/2,3*pi/2,13,0,2)
    modules.append(straight((-34,BASE,-28),(-26,BASE,-28)))
    modules.append(polynomial((-26,BASE,-28),(-12,BASE,-10),(22,0,0),(22,0,0)))
    return modules

def bake():
    modules=build(); dense=[]; lengths=[]; total=0; previous=None
    for m,c in enumerate(modules):
        for k in range(1000):
            t=k/1000; p=evaluate(c,t)
            if previous is not None: total+=norm(sub(p,previous))
            dense.append((m,t)); lengths.append(total); previous=p
    p=evaluate(modules[-1],1); total+=norm(sub(p,previous))
    dense.append((len(modules)-1,1)); lengths.append(total)
    nodes=[]
    for i in range(NODES):
        s=total*i/NODES; j=min(len(lengths)-2,max(0,bisect.bisect_right(lengths,s)-1))
        m,t=dense[j]; span=lengths[j+1]-lengths[j]
        t += (s-lengths[j])/span/1000 if span else 0
        c=modules[m]; p=evaluate(c,t); v=derivative(c,t); a=second(c,t)
        horizontal=math.hypot(v[0],v[2]); curvature=(v[0]*a[2]-v[2]*a[0])/horizontal**3
        nodes.append((p,unit(v),curvature))
    nodes.append(nodes[0])
    def vec(v): return '{'+','.join(f'{x:.8f}f' for x in v)+'}'
    out=['// Generated by tools/generate_grand_spiral.py; do not edit samples.', '#pragma once',
         '#include "track_types.h"', '#include <array>', 'namespace lets_and_go::grand_spiral {',
         'struct Node { TrackVec3 point, tangent; float curvature; };',
         f'inline constexpr float kLength={total:.8f}f;',
         f'inline constexpr std::array<Node,{len(nodes)}> kNodes{{{{']
    out += ['    {'+vec(p)+','+vec(v)+f',{c:.8f}f'+'},' for p,v,c in nodes]
    weights=[0.0]
    for i in range(NODES):
        # Curved modules get a larger share of the same fixed tessellation budget.
        weights.append(weights[-1]+1+min(2.0,abs(nodes[i][2])*12))
    distances=[]
    for i in range(161):
        w=weights[-1]*i/160
        j=min(NODES-1,max(0,bisect.bisect_right(weights,w)-1))
        distances.append(total*(j+(w-weights[j])/(weights[j+1]-weights[j]))/NODES)
    out += ['}};', 'inline constexpr std::array<float,161> kRenderDistances{{',
            ','.join(f'{s:.8f}f' for s in distances), '}};',
            '} // namespace lets_and_go::grand_spiral','']
    (ROOT/'main/apps/app_lets_and_go_racer/model/grand_spiral_data.h').write_text('\n'.join(out))
    clearance=100; crossings=0
    for i,(p,_,_) in enumerate(nodes[:-1]):
        b=nodes[i+1][0]
        for j in range(i+2,NODES):
            if min(j-i,NODES-(j-i))*total/NODES < 7: continue
            q=nodes[j][0]; d=nodes[j+1][0]
            if math.hypot(p[0]-q[0],p[2]-q[2])<3.75: clearance=min(clearance,abs(p[1]-q[1]))
            ux,uz=b[0]-p[0],b[2]-p[2]; vx,vz=d[0]-q[0],d[2]-q[2]
            det=ux*vz-uz*vx
            if abs(det)<1e-8:continue
            t=((q[0]-p[0])*vz-(q[2]-p[2])*vx)/det
            s=((q[0]-p[0])*uz-(q[2]-p[2])*ux)/det
            if 0<=t<1 and 0<=s<1: crossings+=1
    def center(s):
        x=s/(total/NODES);j=min(NODES-1,int(x));t=x-j;step=total/NODES
        a,v,_=nodes[j];b,w,_=nodes[j+1]
        return add(add(mul(a,2*t**3-3*t*t+1),mul(b,-2*t**3+3*t*t)),
                   add(mul(v,step*(t**3-2*t*t+t)),mul(w,step*(t**3-t*t))))
    chord_error=0
    for a,b in zip(distances,distances[1:]):
        for t in (.25,.5,.75):
            chord_error=max(chord_error,norm(sub(center(a+(b-a)*t),add(mul(center(a),1-t),mul(center(b),t)))))
    stats={'mesh_segments':160,'max_center_chord_error':chord_error,'length':total,'nodes':NODES,'max_grade_sine':max(abs(v[1]) for p,v,c in nodes),
           'max_curvature':max(abs(c) for p,v,c in nodes),'near_nonadjacent_center_clearance':clearance,'planar_crossings':crossings}
    (ROOT/'docs/assets/grand-spiral-lab/geometry.json').write_text(json.dumps(stats,indent=2)+'\n')
    print(json.dumps(stats,indent=2))
if __name__=='__main__':bake()
